### ISSUE TITLE
Decoding of negative numbers

### ISSUE THREAD

**Issue by synlestidae** [MatejLach/rustorrent#1]
I notice that the BInt data structure uses u64 whereas the BitTorrent Spec seems to require handling negative integers: https://wiki.theory.org/BitTorrentSpecification#Integers

The BInt data structure and bint_decode function should be changed to allow negative numbers

**Comment by MatejLach** [comment]
Spot on, my bad 😳
Thanks a lot for the pull requests, I've added some comments to it.

**Comment by MatejLach** [comment]
Merged, closing, thanks!
